# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsheet', '0002_auto_20170529_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='sessions',
            field=models.ManyToManyField(related_name='Speakers', to='gsheet.Session'),
        ),
    ]
