# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsheet', '0003_auto_20170529_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='abstract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='isotd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='affliation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
