# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsheet', '0004_auto_20170530_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='contact_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gsheet.Staff'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='otd_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='speaker',
            name='tacec_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='staff',
            name='cellphone',
            field=models.CharField(default='(000)000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='organization',
            field=models.CharField(choices=[('OTD', 'OTD'), ('TACEC', 'TACEC')], default='TACEC', max_length=6),
        ),
    ]
